
---
title: "vizualization-code"
author: "Pence"
date: "7/7/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#install.packages("maps")
library(maps)
#install.packages("tmap")
library(tmap)
#install.packages("plotly")
library(plotly)
```


```{r}
City_Council_Districts  <- read_sf("data/nycc_21b")
School_Districts <- read_sf("data/nysd_21b")
```

```{r}
permits_sf <- st_as_sf(permits_joined, coords = c("Longitude", "Latitude"), crs = 4326)
All_Housing_Permits <- st_transform(permits_sf, 2263)
```

```{r}
permits_landmarks_sf <- st_as_sf(permits_landmarks, coords = c("Longitude", "Latitude"), crs = 4326)
Landmarked_Housing_Permits <- st_transform(permits_landmarks_sf, 2263)
```

```{r}
All_Housing_Permits$address <- paste(All_Housing_Permits$AddressNum, All_Housing_Permits$AddressSt)
Landmarked_Housing_Permits$address <- paste(Landmarked_Housing_Permits$AddressNum, Landmarked_Housing_Permits$AddressSt)
```


```{r}
tmap_mode("view")
Housing_Map<-tm_basemap("Esri.WorldGrayCanvas")+
  tm_shape(All_Housing_Permits)+
tm_bubbles(col = "ClassANet",
           alpha= 0.5,
           size = "ClassANet",
           style="fixed",
           breaks=seq(0, 1500, by=300),
           id="address",
           scale = 0.2,
           border.lwd = 1,
          title.col="Net Housing",
		    popup.vars=c("Council Member: "="council.member", "Permit Year: "="PermitYear","Net Housing: "="ClassANet"),
		    popup.format=list(PermitYear=list(fun=function(PermitYear)formatC(PermitYear, digits=0, format="d"))),
		   shapes.legend = "ClassANet" )+
  tm_shape(Landmarked_Housing_Permits)+
tm_bubbles(col = "ClassANet",
           id= "address",
           alpha= 0.5,
           size = "ClassANet",
           style="fixed",
           breaks=seq(0, 1500, by=300),
           scale = 0.2,
           border.lwd = 1,
           title.col="Net Housing",
		    popup.vars=c("Council Member: "="council.member", "Permit Year: "="PermitYear","Net Housing: "="ClassANet"),
		    popup.format=list(PermitYear=list(fun=function(PermitYear)formatC(PermitYear, digits=0, format="d"))))+
tm_shape(City_Council_Districts)+
  tm_text("CounDist")+
tm_borders(alpha=1)+
  tm_shape(School_Districts)+
  tm_text("SchoolDist")+
tm_borders(alpha=1)
  
tmap_save(Housing_Map, "/Users/ParkerPence/Documents/GitHub/Pence.Parker.Project/images/Housing_Map.html")
```
