---
title: "Pence.Parker.Project"
author: "Pence"
date: "6/24/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
#install.packages("tidyverse")
library(tidyverse)
#install.packages("gdata")
library("gdata")
#install.packages("sf")
library(sf)
```


```{r}
HousingData<- read.csv("data/raw/HousingDB_post2010_inactive_included.csv")
head(HousingData)
councilmemberdata<- read.csv("data/raw/city.council.database.xlsx - data.csv", strip.white=TRUE)
head(councilmemberdata)
```
Separate projects permitted prior to 2010

*How do I save processed data as new data set in github?*

format start and end dates as dates
```{r}
councilmemberdata$start.date <- as.Date(councilmemberdata$start.date, format = "%m/%d/%Y")

councilmemberdata$end.date <- as.Date(councilmemberdata$end.date , format = "%m/%d/%Y")
```

Drop project permits prior to 2014 due to redistricting and any projects permitted in years in which its district had two different councilors
```{r}
post_2013_permits<- subset(HousingData, PermitYear >= 2014)

post_2013_permits_dropped_splits<-subset(post_2013_permits, !(CouncilDst==9 & PermitYear==2017) & !(CouncilDst==12 & PermitYear==2020) & !(CouncilDst==17 & PermitYear==2016) & !(CouncilDst==23 & PermitYear==2015) & !(CouncilDst==24 & PermitYear==2020) & !(CouncilDst==28 & PermitYear==2017) & !(CouncilDst==31 & PermitYear==2020) & !(CouncilDst==37 & PermitYear==2020) & !(CouncilDst==45 & PermitYear==2019) & !(CouncilDst==51 & PermitYear==2015))
```


```{r}
post_2013_councilmembers<- subset(councilmemberdata, start.date >= as.Date("2014-01-01"))
```


Clean council member names
```{r}
str_trim(post_2013_councilmembers$council.member, side = c("both"))
names.split <- strsplit(unlist(post_2013_councilmembers$council.member), " ")

name.first <- sapply(names.split, function(x) x[1])
name.last <- sapply(names.split, function(x)

  if(length(x) == 0) {NA} else if (x[length(x)] %in% c("Jr.", "Jr", "Sr.", "Sr")) { gsub("[[:punct:]]", "", x[length(x) - 1])} else {x[length(x)]})
```


merge data
```{r}
developments-by-council-member<-group_by(post_2013_permits, CouncilDst)
```



